#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
# REGION="us-east-1"  # Set the default region, or replace with desired region
REGION="ca-central-1"  # Set the default region, or replace with desired region

# Check for region-specific creation
aws s3api create-bucket \
--bucket "$BUCKET_NAME" \
--region "$REGION" \
--create-bucket-configuration LocationConstraint="$REGION" \
--query "Location" \
--output text
